name: Deploy OpenFaaS Function

on:
  push:
    branches: [main]
    paths: ["get-quote/**"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup faas-cli
        run: curl -sL https://cli.openfaas.com | sudo sh

      - name: Login to OpenFaaS
        run: echo ${{ secrets.OPENFAAS_PASSWORD }} | faas-cli login --username admin --password-stdin --gateway ${{ secrets.OPENFAAS_URL }}

      - name: Deploy function
        run: faas-cli deploy -f get-quote.yml
